name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  linux-tests:

    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']
        laravel: [9.*, 8.*]
        exclude:
          - laravel: 9.*
            php: 7.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, fileinfo, ftp, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-progress --prefer-stable
                   
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
      
  macos-tests:
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']
        laravel: [9.*, 8.*]
        exclude:
          - laravel: 9.*
            php: 7.4
        
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, fileinfo, ftp, memcached
          tools: composer:v2
          coverage: none
          
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-progress --prefer-stable
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
        
  windows-tests:
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']
        laravel: [9.*, 8.*]
        exclude:
          - laravel: 9.*
            php: 7.4

    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, fileinfo, ftp, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-progress --prefer-stable
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
